class BTN:
    back = "🔙 Назад"
    select_project = "🥢 Выбрать проект"
    create_project = "⛏️ Создать проект"
    leave_project = "❌ Выйти из проекта"
    withdraw_money = "💳 Изъять деньги"
    make_income = "💪 Внести доход"
    about_project = "ℹ О проекте"
    complete_select_tags = "✅ Завершить выбор меток"
    no_comments = "Без комментария"
    create_plan = "⛏ Создать план"
    select_plan = "🥢 Войти в план"
    leave_plan = "❌ Выйти из плана"
    make_payment = "💳 Внести трату"
    about_plan = "ℹ О плане"
    new_period = "🆕 Новый период"
    all_expense_records = "🌀 Все траты"
    pagination_to_start = "<<"
    pagination_to_prev = "<"
    pagination_to_end = ">>"
    pagination_to_next = ">"


class TXT:
    unknown = "Неизвестная команда"
    failure = "Ошибка"
    you_have_leaved_conv = "Вы вышли из беседы"
    ok = "✅"
    only_digits = "Только цифры"
    create_name_question = "Название?"
    what_project = "Какой проект?"
    recently_used_tags = "Ранее введенные метки"
    select_tags_or_type_new = "Выберите метки или введите новую"
    selected_tags = "Выбранные метки:"
    what_comment = "Комментарий?"
    leave_project = "Ты вышел из проекта"
    have_no_projects = "У вас нет проектов"
    have_no_plans = "У вас нет планов"
    what_value_for_new_plan = "C какой суммой начинаем период?"
    you_have_no_tags = "Должен быть хоть один тэг"
    project_already_exist = "Этот проект у вас уже добавлен"
    what_value = "Стоимость?"
    what_amount = "Сумма?"
    what_number_expense = "Номер траты?"


class CMND:
    separator = "_"
    inline_separator = "|"
    append_tag = "append_tag"
    pagination = "pagination"
    pagination_expense_for_project = "pagination_expense_for_project"
    pagination_expense_for_plan = "pagination_expense_for_plan"
    pagination_action_to_start = "<<"
    pagination_action_to_end = ">>"
    pagination_action_to_prev = "<"
    pagination_action_to_next = ">"
    pagination_action_current_page = "-"
    join = "join"
    delete = "delete"
